name: Cronjob CD # name of the workflow

on: 
  # push:
  #   branches: ["main"]
  schedule: # -> cronjob
    - cron: "0 5 * * *"  # -> 5am every single day. Needs default variables(instance_type, instance_name) as it runs automatically. 

  workflow_dispatch:  # -> Allows you to run this workflow manually from the Actions tab. Mannual execution
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7 # using actions/checkout - clonning repo. same as shell command ->  run: git clone [http repo link]
        name: Checkout repository
        # with:
        #   repository: 'may-group-2026-terraform' #using repo other than actions

      - name: Runnin cron job execution
        run: echo "Its a Cron Run. Time is $(date)"